# LLM
llm_model: gpt-3.5-turbo
temperature: 0

# Embedding
vector_store: FAISS
embedding_model: OpenAIEmbeddings

# Document
split_method: recursive
chunk_size: 2000
chunk_overlap: 200

# Logging
log_to_console: True
console_log_level: INFO

log_to_file: True
file_log_level: INFO
log_file_name: ./logs/app.log

log_doc_retrieval: True
doc_retrieval_log_file_name: ./logs/doc_retrieval.log
doc_retrieval_log_level: INFO

# Environment variables
env_path: /Users/chrismannina/cs-projects/school/cs467-capstone/.env
