# LLM
llm_model: gpt-4
temperature: 0

# Embedding
vector_store: FAISS
embedding_model: OpenAIEmbeddings

# Document
split_method: recursive
chunk_size: 2000
chunk_overlap: 200

# Logging
log_to_console: True
console_log_level: ERROR

log_to_file: True
file_log_level: ERROR
log_file_name: ./logs/app.log

log_doc_retrieval: True
doc_retrieval_log_file_name: ./logs/doc_retrieval.log
doc_retrieval_log_level: INFO
