# LLM
llm_model: gpt-3.5-turbo
temperature: 0

# Embedding
vectorstore: FAISS
embedding_model: OpenAIEmbeddings

# Document
document_path: C:\Users\machris\projects\cs467-capstone\files\NCCN_aml_2023_Guidelines.pdf
split_method: recursive
chunk_size: 2000
chunk_overlap: 200
