[browser]
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false

[theme]
primaryColor = "#E694FF"
backgroundColor = "#00172B"
secondaryBackgroundColor = "#0083B8"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[runner]
magicEnabled = false

[application]
showPromo = false
